In [1]:
import numpy as np
import pandas as pd


In [9]:
df=pd.read_csv('heart.csv')

In [10]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [13]:
clf1 = LogisticRegression(max_iter=1000)
clf2 = DecisionTreeClassifier()

In [14]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

DecisionTreeClassifier()

In [15]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [16]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.848780487804878
Accuracy of Decision Trees 0.9804878048780488


In [17]:
confusion_matrix(y_test,y_pred1)

array([[81, 24],
       [ 7, 93]], dtype=int64)

In [18]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))

Logistic Regression Confusion Matrix



0   1
0  81  24
1   7  93

In [19]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))

Decision Tree Confusion Matrix



0    1
0  101    4
1    0  100

In [20]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [21]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
683             0                               0                         0
70              0                               0                         0
231             1                               1                         1
99              1                               1                         1
164             0                               0                         0
291             0                               0                         0
315             1                               1                         1
536             1                               1                         1
183             1                               1                         1
612             0                               0                         0

In [22]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [23]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  81  24
1   7  93
--------------------------------------------------
Precision -  0.7948717948717948
Recall -  0.93
F1 score -  0.8571428571428572


In [24]:
print("For Decision tree Model")
print("-"*50)
cdf=pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision: ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 Score : ",f1_score(y_test,y_pred2))

For Decision tree Model
--------------------------------------------------
     0    1
0  101    4
1    0  100
--------------------------------------------------
Precision:  0.9615384615384616
Recall -  1.0
F1 Score :  0.9803921568627451


##### While calculating precision, sklearn calculates precision for both positive and negative values.But only sends us the value for positive.We cxan check the other value i.e been calculated for neagtives using argument average set to None

In [25]:
precision_score(y_test,y_pred1,average=None)

array([0.92045455, 0.79487179])

In [26]:
precision_score(y_test,y_pred2,average=None)

array([1.        , 0.96153846])

##### Same happens with recall score

In [27]:
recall_score(y_test,y_pred1,average=None)

array([0.77142857, 0.93      ])

In [28]:
recall_score(y_test,y_pred2,average=None)

array([0.96190476, 1.        ])